In [1]:
from torch import nn
import torch

In [2]:
class linear_regression(nn.Module):
    def __init__(self,input_size,output_size):
        super(linear_regression,self).__init__()
        self.linear=nn.Linear(input_size,output_size)
    def forward(self,x):
        yhat=self.linear(x)
        return yhat

create a linear regression object, as our input and output will be two we set the parameters accordingly

In [3]:
model=linear_regression(1,10)
model(torch.tensor([1.0]))

tensor([ 1.9657,  0.4364, -0.2009,  0.5081, -1.0170, -0.1788,  0.8406, -0.7493,
        -0.5740,  0.4300], grad_fn=<ViewBackward0>)

In [4]:
# we can see the parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.9845],
         [-0.1059],
         [-0.1142],
         [-0.4148],
         [-0.6591],
         [-0.0413],
         [-0.1031],
         [-0.1164],
         [-0.2791],
         [ 0.6470]], requires_grad=True),
 Parameter containing:
 tensor([ 0.9811,  0.5423, -0.0867,  0.9229, -0.3578, -0.1375,  0.9438, -0.6329,
         -0.2948, -0.2170], requires_grad=True)]

In [5]:
X=torch.tensor([[1.0],[1.0],[3.0]])

In [6]:
Yhat=model(X)
Yhat

tensor([[ 1.9657,  0.4364, -0.2009,  0.5081, -1.0170, -0.1788,  0.8406, -0.7493,
         -0.5740,  0.4300],
        [ 1.9657,  0.4364, -0.2009,  0.5081, -1.0170, -0.1788,  0.8406, -0.7493,
         -0.5740,  0.4300],
        [ 3.9347,  0.2246, -0.4292, -0.3215, -2.3352, -0.2613,  0.6343, -0.9821,
         -1.1323,  1.7240]], grad_fn=<AddmmBackward0>)